#Makefile for compiing & executing the program
#OS-Labs at Technische Universität Darmstadt

CFLAG= -Wall
CC=gcc
RM= rm -f 


all: process_mng

process_mng: 
	$(CC) $(CFLAG) -o process_mng process-management.c

clean:
	$(RM) process_mng
