#Makefile for compiing & executing the program
#OS-Labs at Technische Universität Darmstadt

all: process-management.c
	gcc -Wall -o process-management.o process-management.c
	./process-management.o
clean:
	$(RM) process-management.o
