all: task1 task2 task3 task4 task5

task1:
	make -C 1/
task2:
	make -C 2/
task3:
	make -C 3/
task4:
	make -C 4/
task5:
	make -C 5/
clean:
	make clean -C 1/
	make clean -C 2/
	make clean -C 3/
	make clean -C 4/
	make clean -C 5/
