#Makefile for compiing & executing the program
#OS-Labs at Technische Universität Darmstadt

all: process-management.c
	gcc -Wall -o posix-thread.o posix-thread.c
	./posix-thread.o
clean:
	$(RM) posix-thread.o
